### ISSUE TITLE
subprocess.py

### ISSUE THREAD

**Issue by quattrinia** [RemiAllio/MitoFinder#41]
Hi Remi,

Have you seen this error before?  I checked my /usr/lib/python2.7 directory and that subprocess.py file is present.

Cheers,
Andrea

Formatting database for mitochondrial contigs identification...
Running mitochondrial contigs identification step...

MitoFinder found 3 contigs matching provided mitochondrial reference(s)
Did not check for circularization

Creating summary statistics for mtDNA contig 1

Traceback (most recent call last):
  File "/data/mcfadden/aquattrini/PROGRAMS/MitoFinder/mitofinder", line 1209, in <module>
    rename = Popen(args1, stdout=open(os.devnull, 'wb'))
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by RemiAllio** [comment]
Hi Andrea,

We usually get this error when one of the files necessary for the execution of the subprocess is missing or cannot be opened by the program (restricted permission).

Can you confirm that the file "rename_fasta_seqID.py" exists in the MitoFinder directory. 
If so, could you try to run ```chmod 777 rename_fasta_seqID.py``` and try again? 

Let me know what happens.
Sorry for the inconvenience,
Best regards,
Rémi

**Comment by quattrinia** [comment]
That didn't appear to work. I am trying to get this re-installed on an HPC that I had it working on.  I currently have it running on another server as well (working off of 2 HPCs :) 

 Anyways, it was working, and then just stopped and spit out the error. I then removed and reinstalled, and get the error noted below.

  Now running MitoFinder ...

Start time : 2022-11-28 10:35:00

Job name = S023

Creating Output directory : /data/mcfadden/smoaleman/hailey/mitos/antipath/S023
All results will be written here

Program folders:
MEGAHIT = /data/mcfadden/aquattrini/PROGRAMS/MitoFinder/megahit/
MetaSPAdes folder = /data/mcfadden/aquattrini/PROGRAMS/MitoFinder/metaspades/bin/
IDBA-UD folder = /data/mcfadden/aquattrini/PROGRAMS/MitoFinder/idba/bin/
Blast folder = /data/mcfadden/aquattrini/PROGRAMS/MitoFinder/blast/bin/
ARWEN folder = /data/mcfadden/aquattrini/PROGRAMS/MitoFinder/arwen/
MiTFi folder = /data/mcfadden/aquattrini/PROGRAMS/MitoFinder/mitfi/
tRNAscan-SE folder = /data/mcfadden/aquattrini/PROGRAMS/MitoFinder/trnascanSE/tRNAscan-SE-2.0/

Gene named "HEG" in the reference file is not recognized by MitoFinder.
MitoFinder will try to annotate it.

Formatting database for mitochondrial contigs identification...
Running mitochondrial contigs identification step...

MitoFinder found 3 contigs matching provided mitochondrial reference(s)
Did not check for circularization


Creating summary statistics for mtDNA contig 1

Traceback (most recent call last):
  File "/data/mcfadden/aquattrini/PROGRAMS/MitoFinder/mitofinder", line 1209, in <module>
    rename = Popen(args1, stdout=open(os.devnull, 'wb'))
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by RemiAllio** [comment]
I am very sorry for the inconvenience..
To be sure it's not an installation or permission problem, could you please try to use the [singularity image of MitoFinder v1.4.1](https://cloud.sylabs.io/library/remiallio/default/mitofinder)?

Let me know what you think,
Best,
Rémi

**Comment by quattrinia** [comment]
Trying to get singularity installed. Running into some issues but working on it...thanks!

**Comment by RemiAllio** [comment]
Hi,

It may be too late, but Benoit Nabholz seems to have found a solution to solve the problem as suggested [here](https://github.com/RemiAllio/MitoFinder/issues/44#issuecomment-1421496654).
Could you give it a try and let us know if it works like that for you as well?

Thank you in advance,
Best,
Rémi

**Comment by DeadlineWasYesterday** [comment]
> Hi,
> 
> It may be too late, but Benoit Nabholz seems to have found a solution to solve the problem as suggested [here](https://github.com/RemiAllio/MitoFinder/issues/44#issuecomment-1421496654). Could you give it a try and let us know if it works like that for you as well?
> 
> Thank you in advance, Best, Rémi

This solved my problems too.
