### ISSUE TITLE
ValueError: Feature references another sequence.

### ISSUE THREAD

**Issue by S-111** [RemiAllio/MitoFinder#66]
Hi.
I received an error with the following command.
Is there a solution?
I am using version 1.4.2.

command
`mitofinder --new-genes --max-contig-size 1504145 -j ptg000136l.annotation -a ptg000136l.mitogenome.fa -r /home/PP816722.1.gb -o 1 -p 2 --circular-size 8000`

error
`Traceback (most recent call last):
  File "/home/MitoFinder/mitofinder", line 576, in <module>
    if not "A" in feature.extract(record).seq.upper() and not "C" in feature.extract(record).seq.upper() and not "G" in feature.extract(record).seq.upper() and not "T" in feature.extract(record).seq.upper():
  File "/lustre7/home/MitoFinder/Bio/SeqFeature.py", line 339, in extract
    return self.location.extract(parent_sequence)
  File "/lustre7/home/MitoFinder/Bio/SeqFeature.py", line 1211, in extract
    parts = [loc.extract(parent_sequence) for loc in self.parts]
  File "/lustre7/home/MitoFinder/Bio/SeqFeature.py", line 917, in extract
    raise ValueError("Feature references another sequence.")
ValueError: Feature references another sequence.`

**Comment by S-111** [comment]
The cause of the error seems to be that some features refer to parts of other nucleotides in the GenBank file given as input.
For example, this is the part
`join(complement(60377..62690),31330..31351,complement(PP816723.1:49336..50808))`
The sequence name of the input GenBank file is PP816722.1, but it partially references the PP816723.1 sequence.

If the part of the PP816723.1 sequence that references this PP816723.1 sequence is removed, the error no longer occurs.
Example after modification.
`join(complement(60377..62690),31330..31351)`
